'use strict';

/**
 * Generates a Markdown bundle size report and writes it to a file.
 * Also returns the markdown string from write() so the pipeline can
 * forward it as a GitLab MR comment without reading the file back.
 */

const ReportWriter = require('./ReportWriter');
const config = require('../config');
const { formatBytes, formatBytesAbs } = require('../services/Formatter');
const { writeText } = require('../infrastructure/FileSystemPort');

class MarkdownReportWriter extends ReportWriter {
  /**
   * @param {string} outputPath - File path to write the report to
   */
  constructor(outputPath) {
    super();
    this.outputPath = outputPath;
  }

  /**
   * @param {Array}  comparisons
   * @param {object} context - { baseBranch, headBranch }
   * @returns {string} Markdown string
   */
  generate(comparisons, context) {
    const { baseBranch, headBranch } = context;
    const hasWarnings = comparisons.some((c) => c.status.includes('⚠️'));
    const hasFails    = comparisons.some((c) => c.status.includes('🔴'));

    const summary = hasFails
      ? '🔴 **CSS bundle size check FAILED** — one or more bundles exceeded the failure threshold.'
      : hasWarnings
      ? '⚠️ **CSS bundle size check WARNING** — one or more bundles exceeded the warning threshold.'
      : '✅ **CSS bundle size check passed** — all bundles are within thresholds.';

    const rows = comparisons
      .map((c) => {
        const diffStr =
          c.diffBytes === 0
            ? '—'
            : `${formatBytes(c.diffBytes)} (${c.diffPercent > 0 ? '+' : ''}${c.diffPercent}%)`;
        return `| ${c.name} | ${formatBytesAbs(c.baseSize)} | ${formatBytesAbs(c.newSize)} | ${diffStr} | ${c.status} |`;
      })
      .join('\n');

    const { warnBytes, warnPercent, failBytes, failPercent } = config.thresholds;

    return `## 📦 CSS Bundle Size Report

${summary}

| Library Name | Base Size (gzip) | New Size (gzip) | Diff (+/−) | Status |
|---|---|---|---|---|
${rows}

> **Thresholds:** Warn at +${formatBytesAbs(warnBytes)} or +${warnPercent}% · Fail at +${formatBytesAbs(failBytes)} or +${failPercent}%
> **Branches:** \`${baseBranch}\` → \`${headBranch}\`
> _Sizes shown are gzip-compressed. Generated by CSS Bundle Tracker._
`;
  }

  /**
   * Generate and write the report to disk.
   * Returns the markdown string so callers can reuse it (e.g. for MR comments).
   *
   * @param {Array}  comparisons
   * @param {object} context - { baseBranch, headBranch }
   * @returns {string}
   */
  write(comparisons, context) {
    const markdown = this.generate(comparisons, context);
    writeText(this.outputPath, markdown);
    console.log(`✅ Markdown report        → ${this.outputPath}`);
    return markdown;
  }
}

module.exports = MarkdownReportWriter;
