'use strict';

/**
 * Markdown report reporter.
 * Generates a Markdown table suitable for GitLab MR comments or artifact uploads.
 *
 * Pure function — no I/O, no side effects.
 */

const config = require('../config');
const { formatBytes, formatBytesAbs } = require('../format');

/**
 * Generate a Markdown bundle size report.
 *
 * @param {Array}  comparisons - Output of compareSizes()
 * @param {string} baseBranch  - Target branch name (display only)
 * @param {string} headBranch  - Source branch name (display only)
 * @returns {string} Markdown string
 */
function generateMarkdownTable(comparisons, baseBranch, headBranch) {
  const hasWarnings = comparisons.some((c) => c.status.includes('⚠️'));
  const hasFails    = comparisons.some((c) => c.status.includes('🔴'));

  const summary = hasFails
    ? '🔴 **CSS bundle size check FAILED** — one or more bundles exceeded the failure threshold.'
    : hasWarnings
    ? '⚠️ **CSS bundle size check WARNING** — one or more bundles exceeded the warning threshold.'
    : '✅ **CSS bundle size check passed** — all bundles are within thresholds.';

  const rows = comparisons
    .map((c) => {
      const diffStr =
        c.diffBytes === 0
          ? '—'
          : `${formatBytes(c.diffBytes)} (${c.diffPercent > 0 ? '+' : ''}${c.diffPercent}%)`;
      return `| ${c.name} | ${formatBytesAbs(c.baseSize)} | ${formatBytesAbs(c.newSize)} | ${diffStr} | ${c.status} |`;
    })
    .join('\n');

  const { warnBytes, warnPercent, failBytes, failPercent } = config.thresholds;

  return `## 📦 CSS Bundle Size Report

${summary}

| Library Name | Base Size (gzip) | New Size (gzip) | Diff (+/−) | Status |
|---|---|---|---|---|
${rows}

> **Thresholds:** Warn at +${formatBytesAbs(warnBytes)} or +${warnPercent}% · Fail at +${formatBytesAbs(failBytes)} or +${failPercent}%
> **Branches:** \`${baseBranch}\` → \`${headBranch}\`
> _Sizes shown are gzip-compressed. Generated by CSS Bundle Tracker._
`;
}

module.exports = { generateMarkdownTable };
